### ISSUE TITLE
Missing link to jypyter notebook

### ISSUE THREAD

**Issue by tjelvar-olsson** [JIC-CSB/dtoolai#8]
In here: https://dtoolai.readthedocs.io/en/latest/training.html#what-the-code-is-doing

it says that we provide a jupyter notebook, however there is no link to it and I can't find it in the git repository.

1. Add it to the git repository
2. Add an explanation to the docs on how to find it

**Comment by mrmh2** [comment]
Added notebooks to git repository and linked in documentation.
